
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: knowledge_based_gpt_development

test:
  <<: *default
  database: knowledge_based_gpt_test

production:
  <<: *default
  database: knowledge_based_gpt_production
  username: knowledge_based_gpt
  password: <%= ENV["KNOWLEDGE_BASED_GPT_DATABASE_PASSWORD"] %>
